defaults: &defaults
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  
development:
   <<: *defaults
   database: db/development.sqlite3
  
test:
   <<: *defaults
   database: db/test.sqlite3

production:
   adapter: postgresql
   encoding: utf8
   database: qtrack
   pool: 5
   username: 
   password:
